### ISSUE TITLE
以统计数量多的换行风格为文件换行格式

### ISSUE THREAD

**Issue by Jackarain** [avplayer/TextTools#2]
统计一下文件里的crlf和lf的数量，然后save的时候，以数量多的为准，加一个这样的选项，这样有一个好处
就是，在使用某些库的时候，库的crlf和你项目并不一至时，save的时候，不会影响到库的crlf。

**Comment by hyqhyq3** [comment]
#1ad04c80a53471d505c9e9a3f00361a58bb85172
