### ISSUE TITLE
NullReferenceException in vs2017

### ISSUE THREAD

**Issue by stamerlan** [avplayer/TextTools#3]
Hello,

The problem occurred on vs2017pro 15.7.3 during open folder (File->Open->Folder...):

**vs info**:
Microsoft Visual Studio Professional 2017 
Version 15.7.3
VisualStudio.15.Release/15.7.3+27703.2026
Microsoft .NET Framework
Version 4.7.02558
Installed Version: Professional
Visual C++ 2017   00370-20005-95143-AA629
Microsoft Visual C++ 2017
ASP.NET and Web Tools 2017   15.0.40522.0
ASP.NET and Web Tools 2017
ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.
C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Cookiecutter   15.7.18131.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.
Debugging Tools for Windows   10.0.16292.1001
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.
File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer
GitHub.VisualStudio   2.5.2.2566
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
JavaScript Language Service   2.0
JavaScript Language Service
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards
Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package
NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info
Python   15.7.18131.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
Python - IronPython support   15.7.18131.1
Provides templates and integration for IronPython-based projects.
Python - Profiling support   15.7.18131.1
Profiling support for Python projects.
ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info
Show Missing Files   1.0
Find files references in project files that don't exist on disk, and optionally files that do exist on disk that aren't included in a project. 
Runs on Build. Missing files are listed in Error List window.
Syntax Highlighting Pack   2.8.133
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...
Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Visual C++ for Cross Platform Mobile Development (Android)   15.0.27625.00
Visual C++ for Cross Platform Mobile Development (Android)
Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker
Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker
Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
Windows Driver Kit   10.0.16292.1001
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)
Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Also activity log attached
[ActivityLog.xml.txt](https://github.com/avplayer/convert-line-ending/files/2094442/ActivityLog.xml.txt)

**Comment by Jackarain** [comment]
fixed
